/** Generated by Hine */
import { Action } from 'hine-next';
import State from './input.hine';


function action1() {}
function action2() {}


;const state = new State();
state.monitor({
    actions: {
		action1: new Action({ run: action1 }),
		action2: new Action({ run: action2 })
    },
	entry: [
		{
			actions: ["action1", "action2"],
		}
    ],
});

export default state;