import { b, print } from 'code-red';

/**
 * @param {{ on: Record<string, string>; }} config
 */
export function generate(config) {
	const output = b`
/** Generated by Hine */
import {
	State
} from 'hine-next';
const config = ${JSON.stringify(config, null, 4)};

export default class Machine extends State {
	constructor() {
		super(config);
	}
}`;
	return print(output);
}
