/**
 * @param {{ on: Record<string, any>; }} config
 */
export function generate(config) {
	const output = `/** Generated by Hine */
import {
	State
} from 'hine-next';
const config = ${JSON.stringify(config, null, 4)};

export default class Machine extends State {
	constructor() {
		super(config);
	}
};`;
	return output;
}
