import { dedent } from './string';

/**
 * @param {{ on: Record<string, any>; }} config
 */
export function generateMachine(config) {
	const output = `/** Generated by Hine */
import {
	State
} from 'hine-next';
const config = ${JSON.stringify(config, null, 4)};

export default class Machine extends State {
	constructor() {
		super(config);
	}
};`;
	return output;
}

/**
 * @param {import('../processor/types').MonitorProgram} cir
 */
export function generateMonitor(cir) {
	const output = `/** Generated by Hine */
import { Action } from 'hine-next';
import State from '${cir.monitor.src}';

${dedent(cir.script.content)}

;const state = new State();
state.monitor({
    actions: {
		${cir.monitor.actions
			.map((action) => `${action.name}: new Action({ run: ${action.value} })`)
			.join(',\n		')}
    },
	entry: [
		{
			actions: [${cir.monitor.entry
				.map((action) => JSON.stringify(action.name))
				.join(', ')}],
		}
    ],
});

export default state;`;
	return output;
}
