/** Generated by Hine */
import {
	State
} from 'hine-next';
const config = {
    "on": {
        "event1": [
            {
                "actions": [
                    "action1"
                ]
            }
        ]
    }
};

export default class Machine extends State {
	constructor() {
		super(config);
	}
};